spring:
  datasource:
    url: jdbc:postgresql://156.67.110.11:5432/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    #    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+6
          lob:
            non_contextual_creation: true
        show_sql: false
        format_sql: false